# Generated by Django 5.2.11 on 2026-02-15 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Naqd'), ('card', 'Plastik karta')], default='cash', max_length=10),
        ),
    ]
